-- Enable UUID extension if not enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Secure SQL execution RPC wrapper for HTTP IPv4 routing (Supports SELECT, INSERT/UPDATE/DELETE with RETURNING, and direct writes/DDL)
CREATE OR REPLACE FUNCTION exec_sql(query_text text)
RETURNS jsonb AS $$
DECLARE
  result jsonb;
  upper_query text;
BEGIN
  -- Strip all leading whitespaces, including newlines and tabs, then convert to uppercase
  upper_query := regexp_replace(upper(query_text), '^\s+', '');
  
  IF upper_query LIKE 'SELECT%' OR upper_query LIKE 'WITH%' THEN
    -- SELECT and normal CTEs wrapped in standard SELECT FROM
    EXECUTE 'SELECT coalesce(jsonb_agg(t), ''[]''::jsonb) FROM (' || query_text || ') t' INTO result;
  ELSIF query_text ~* '\yreturning\y' THEN
    -- Data-modifying queries (INSERT/UPDATE/DELETE) with RETURNING clause
    EXECUTE 'WITH t AS (' || query_text || ') SELECT coalesce(jsonb_agg(t), ''[]''::jsonb) FROM t' INTO result;
  ELSE
    -- Data-modifying queries (INSERT/UPDATE/DELETE) without RETURNING, or DDL
    EXECUTE query_text;
    result := '[]'::jsonb;
  END IF;
  
  RETURN result;
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('error', SQLERRM);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 1. LANGUAGES TABLE
CREATE TABLE IF NOT EXISTS languages (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  code VARCHAR(10) NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CATEGORY TABLE
CREATE TABLE IF NOT EXISTS categories (
  id SERIAL PRIMARY KEY,
  language_id INTEGER NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(language_id, name)
);

-- 3. RSS SOURCE TABLE
CREATE TABLE IF NOT EXISTS rss_sources (
  id SERIAL PRIMARY KEY,
  language_id INTEGER NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  source_name VARCHAR(100) NOT NULL,
  rss_url TEXT NOT NULL UNIQUE,
  enabled BOOLEAN NOT NULL DEFAULT true,
  priority INTEGER NOT NULL DEFAULT 1,
  last_checked_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ARTICLE TABLE
CREATE TABLE IF NOT EXISTS articles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  language_id INTEGER NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  source_url TEXT NOT NULL UNIQUE,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  reading_time INTEGER NOT NULL DEFAULT 0,
  is_saved BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true
);

-- 5. SAVED ARTICLES TABLE
CREATE TABLE IF NOT EXISTS saved_articles (
  id SERIAL PRIMARY KEY,
  article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE UNIQUE,
  saved_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. SYNC LOGS TABLE
CREATE TABLE IF NOT EXISTS sync_logs (
  id SERIAL PRIMARY KEY,
  rss_source_id INTEGER NOT NULL REFERENCES rss_sources(id) ON DELETE CASCADE,
  status VARCHAR(20) NOT NULL, -- 'success', 'failure'
  articles_found INTEGER NOT NULL DEFAULT 0,
  articles_imported INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. SYSTEM LOGS TABLE
CREATE TABLE IF NOT EXISTS system_logs (
  id SERIAL PRIMARY KEY,
  log_level VARCHAR(20) NOT NULL,
  action VARCHAR(50) NOT NULL,
  message TEXT NOT NULL,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_categories_language ON categories(language_id);
CREATE INDEX IF NOT EXISTS idx_rss_sources_lang_cat ON rss_sources(language_id, category_id);
CREATE INDEX IF NOT EXISTS idx_articles_lang_cat ON articles(language_id, category_id);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_published_at ON articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_saved_articles_article_id ON saved_articles(article_id);
CREATE INDEX IF NOT EXISTS idx_sync_logs_rss_source ON sync_logs(rss_source_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_action ON system_logs(action);


-- =========================================================================
--                               SEED DATA
-- =========================================================================

-- 1. Populating languages
INSERT INTO languages (id, name, code, enabled) VALUES
(1, 'English', 'en', true),
(2, 'Hindi', 'hi', true),
(3, 'Telugu', 'te', true),
(4, 'Tamil', 'ta', true),
(5, 'Bengali', 'bn', true),
(6, 'Gujarati', 'gu', true),
(7, 'Kannada', 'kn', true),
(8, 'Malayalam', 'ml', true),
(9, 'Marathi', 'mr', true),
(10, 'Odia', 'or', true),
(11, 'Punjabi', 'pa', true),
(12, 'Urdu', 'ur', true),
(13, 'Nepali', 'ne', true),
(14, 'Arabic', 'ar', true),
(15, 'French', 'fr', true),
(16, 'Spanish', 'es', true),
(17, 'Filipino', 'tl', true)
ON CONFLICT (id) DO UPDATE SET enabled = EXCLUDED.enabled;

-- Reset serial sequences for languages
SELECT setval('languages_id_seq', 17);

-- 2. Populating categories
INSERT INTO categories (id, language_id, name, enabled) VALUES
-- English Categories (id: 1 - 16)
(1, 1, 'India', true),
(2, 1, 'World', true),
(3, 1, 'States', true),
(4, 1, 'Sports', true),
(5, 1, 'Cricket', true),
(6, 1, 'Technology', true),
(7, 1, 'Business', true),
(8, 1, 'Health', true),
(9, 1, 'Entertainment', true),
(10, 1, 'Science', true),
(11, 1, 'Education', true),
(12, 1, 'Economy', true),
(13, 1, 'Politics', true),
(14, 1, 'Lifestyle', true),
(15, 1, 'People', true),
(16, 1, 'Arts & Culture', true),

-- Hindi Categories (id: 17 - 28)
(17, 2, 'भारत', true),
(18, 2, 'दुनिया', true),
(19, 2, 'राज्य', true),
(20, 2, 'खेल', true),
(21, 2, 'क्रिकेट', true),
(22, 2, 'टेक्नोलॉजी', true),
(23, 2, 'बिज़नेस', true),
(24, 2, 'सेहत', true),
(25, 2, 'मनोरंजन', true),
(26, 2, 'विज्ञान', true),
(27, 2, 'शिक्षा', true),
(28, 2, 'लाइफ़स्टाइल', true),

-- Telugu Categories (id: 29 - 41)
(29, 3, 'ఆంధ్రప్రదేశ్', true),
(30, 3, 'తెలంగాణ', true),
(31, 3, 'భారతదేశం', true),
(32, 3, 'ప్రపంచం', true),
(33, 3, 'క్రీడలు', true),
(34, 3, 'క్రికెట్', true),
(35, 3, 'సాంకేతికత', true),
(36, 3, 'వ్యాపారం', true),
(37, 3, 'ఆరోగ్యం', true),
(38, 3, 'వినోదం', true),
(39, 3, 'విజ్ఞానశాస్త్రం', true),
(40, 3, 'రాజకీయాలు', true),
(41, 3, 'జీవనశైలి', true),

-- Tamil Categories (id: 42 - 54)
(42, 4, 'தமிழ்நாடு', true),
(43, 4, 'இந்தியா', true),
(44, 4, 'உலகம்', true),
(45, 4, 'வாழ்க்கை முறை', true),
(46, 4, 'கல்வி', true),
(47, 4, 'விளையாட்டு', true),
(48, 4, 'கிரிக்கெட்', true),
(49, 4, 'தொழில்நுட்பம்', true),
(50, 4, 'வணிகம்', true),
(51, 4, 'சுகாதாரம்', true),
(52, 4, 'பொழுதுபோக்கு', true),
(53, 4, 'அறிவியல்', true),
(54, 4, 'வாகனங்கள்', true),

-- Bengali Categories (id: 55 - 65)
(55, 5, 'পশ্চিমবঙ্গ', true),
(56, 5, 'ভারত', true),
(57, 5, 'বিশ্ব', true),
(58, 5, 'রাজনীতি', true),
(59, 5, 'ব্যবসা', true),
(60, 5, 'প্রযুক্তি', true),
(61, 5, 'স্বাস্থ্য', true),
(62, 5, 'খেলা', true),
(63, 5, 'ক্রিকেট', true),
(64, 5, 'বিনোদন', true),
(65, 5, 'শিক্ষা', true),

-- Gujarati Categories (id: 66 - 80)
(66, 6, 'ગુજરાત', true),
(67, 6, 'ભારત', true),
(68, 6, 'વિશ્વ', true),
(69, 6, 'રાજકારણ', true),
(70, 6, 'બિઝનેસ', true),
(71, 6, 'ટેક્નોલોજી', true),
(72, 6, 'વિજ્ઞાન', true),
(73, 6, 'આરોગ્ય', true),
(74, 6, 'રમતગમત', true),
(75, 6, 'ક્રિકેટ', true),
(76, 6, 'મનોરંજન', true),
(77, 6, 'શિક્ષણ', true),
(78, 6, 'નોકરીઓ', true),
(79, 6, 'ઓટો', true),
(80, 6, 'કૃષિ', true),

-- Kannada Categories (id: 81 - 99)
(81, 7, 'ಕರ್ನಾಟಕ', true),
(82, 7, 'ಭಾರತ', true),
(83, 7, 'ವಿಶ್ವ', true),
(84, 7, 'ರಾಜಕೀಯ', true),
(85, 7, 'ವಾಣಿಜ್ಯ', true),
(86, 7, 'ತಂತ್ರಜ್ಞಾನ', true),
(87, 7, 'ವಿಜ್ಞಾನ', true),
(88, 7, 'ಆರೋಗ್ಯ', true),
(89, 7, 'ಕ್ರೀಡೆ', true),
(90, 7, 'ಕ್ರಿಕೆಟ್', true),
(91, 7, 'ಮನರಂಜನೆ', true),
(92, 7, 'ಸಿನಿಮಾ', true),
(93, 7, 'ಜೀವನಶೈಲಿ', true),
(94, 7, 'ಶಿಕ್ಷಣ', true),
(95, 7, 'ಉದ್ಯೋಗಗಳು', true),
(96, 7, 'ಕೃಷಿ', true),
(97, 7, 'ಆಟೋಮೊಬೈಲ್', true),
(98, 7, 'ಸಂಸ್ಕೃತಿ', true),
(99, 7, 'ಪ್ರವಾಸೋದ್ಯಮ', true),

-- Malayalam Categories (id: 100 - 118)
(100, 8, 'കേരളം', true),
(101, 8, 'ഇന്ത്യ', true),
(102, 8, 'ലോകം', true),
(103, 8, 'രാഷ്ട്രീയം', true),
(104, 8, 'ബിസിനസ്', true),
(105, 8, 'സാങ്കേതികവിദ്യ', true),
(106, 8, 'ശാസ്ത്രം', true),
(107, 8, 'ആരോഗ്യം', true),
(108, 8, 'കായികം', true),
(109, 8, 'ക്രിക്കറ്റ്', true),
(110, 8, 'വിനോദം', true),
(111, 8, 'സിനിമ', true),
(112, 8, 'ജീവിതശൈലി', true),
(113, 8, 'വിദ്യാഭ്യാസം', true),
(114, 8, 'തൊഴിൽ വാർത്തകൾ', true),
(115, 8, 'കൃഷി', true),
(116, 8, 'ഓട്ടോമൊബൈൽ', true),
(117, 8, 'സംസ്കാരം', true),
(118, 8, 'യാത്ര', true),

-- Marathi Categories (id: 119 - 140)
(119, 9, 'मुंबई', true),
(120, 9, 'महाराष्ट्र', true),
(121, 9, 'भारत', true),
(122, 9, 'जग', true),
(123, 9, 'राजकारण', true),
(124, 9, 'व्यवसाय', true),
(125, 9, 'तंत्रज्ञान', true),
(126, 9, 'विज्ञान', true),
(127, 9, 'आरोग्य', true),
(128, 9, 'महिला', true),
(129, 9, 'क्रीडा', true),
(130, 9, 'क्रिकेट', true),
(131, 9, 'मनोरंजन', true),
(132, 9, 'चित्रपट', true),
(133, 9, 'जीवनशैली', true),
(134, 9, 'शिक्षण', true),
(135, 9, 'नोकरी', true),
(136, 9, 'कृषी', true),
(137, 9, 'ऑटोमोबाईल', true),
(138, 9, 'प्रवास', true),
(139, 9, 'संस्कृती', true),
(140, 9, 'स्टार्टअप्स', true),

-- Odia Categories (id: 141 - 161)
(141, 10, 'ଓଡ଼ିଶା', true),
(142, 10, 'ଭୁବନେଶ୍ୱର', true),
(143, 10, 'ଭାରତ', true),
(144, 10, 'ବିଶ୍ୱ', true),
(145, 10, 'ରାଜନୀତି', true),
(146, 10, 'ବ୍ୟବସାୟ', true),
(147, 10, 'ପ୍ରଯୁକ୍ତି', true),
(148, 10, 'ବିଜ୍ଞାନ', true),
(149, 10, 'ସ୍ୱାସ୍ଥ୍ୟ', true),
(150, 10, 'କ୍ରୀଡା', true),
(151, 10, 'କ୍ରିକେଟ', true),
(152, 10, 'ମନୋରଞ୍ଜନ', true),
(153, 10, 'ସିନେମା', true),
(154, 10, 'ଶିକ୍ଷା', true),
(155, 10, 'ଚାକିରି', true),
(156, 10, 'ଜୀବନଶୈଳୀ', true),
(157, 10, 'କୃଷି', true),
(158, 10, 'ଅଟୋ', true),
(159, 10, 'ସଂସ୍କୃତି', true),
(160, 10, 'ଭ୍ରମଣ', true),
(161, 10, 'ଷ୍ଟାର୍ଟଅପ୍', true),

-- Punjabi Categories (id: 162 - 182)
(162, 11, 'ਪੰਜਾਬ', true),
(163, 11, 'ਚੰਡੀਗੜ੍ਹ', true),
(164, 11, 'ਭਾਰਤ', true),
(165, 11, 'ਦੁਨੀਆ', true),
(166, 11, 'ਰਾਜਨੀਤੀ', true),
(167, 11, 'ਕਾਰੋਬਾਰ', true),
(168, 11, 'ਟੈਕਨੋਲੋਜੀ', true),
(169, 11, 'ਵਿਗਿਆਨ', true),
(170, 11, 'ਸਿਹਤ', true),
(171, 11, 'ਖੇਡਾਂ', true),
(172, 11, 'ਕ੍ਰਿਕਟ', true),
(173, 11, 'ਮਨੋਰੰਜਨ', true),
(174, 11, 'ਫ਼ਿਲਮਾਂ', true),
(175, 11, 'ਸਿੱਖਿਆ', true),
(176, 11, 'ਨੌਕਰੀਆਂ', true),
(177, 11, 'ਜੀਵਨ ਸ਼ੈਲੀ', true),
(178, 11, 'ਖੇਤੀਬਾੜੀ', true),
(179, 11, 'ਆਟੋ', true),
(180, 11, 'ਸੱਭਿਆਚਾਰ', true),
(181, 11, 'ਯਾਤਰਾ', true),
(182, 11, 'ਸਟਾਰਟਅਪ', true),

-- Urdu Categories (id: 183 - 200)
(183, 12, 'پاکستان', true),
(184, 12, 'ہندوستان', true),
(185, 12, 'دنیا', true),
(186, 12, 'سیاست', true),
(187, 12, 'کاروبار', true),
(188, 12, 'ٹیکنالوجی', true),
(189, 12, 'سائنس', true),
(190, 12, 'صحت', true),
(191, 12, 'کھیل', true),
(192, 12, 'کرکٹ', true),
(193, 12, 'تفریح', true),
(194, 12, 'تعلیم', true),
(195, 12, 'طرزِ زندگی', true),
(196, 12, 'زراعت', true),
(197, 12, 'آٹو', true),
(198, 12, 'ثقافت', true),
(199, 12, 'سفر', true),
(200, 12, 'اسٹارٹ اپس', true),

-- Nepali Categories (id: 201 - 219)
(201, 13, 'नेपाल', true),
(202, 13, 'काठमाडौं', true),
(203, 13, 'भारत', true),
(204, 13, 'विश्व', true),
(205, 13, 'राजनीति', true),
(206, 13, 'व्यापार', true),
(207, 13, 'प्रविधि', true),
(208, 13, 'विज्ञान', true),
(209, 13, 'स्वास्थ्य', true),
(210, 13, 'खेलकुद', true),
(211, 13, 'क्रिकेट', true),
(212, 13, 'मनोरञ्जन', true),
(213, 13, 'शिक्षा', true),
(214, 13, 'जीवनशैली', true),
(215, 13, 'कृषि', true),
(216, 13, 'अटोमोबाइल', true),
(217, 13, 'संस्कृति', true),
(218, 13, 'यात्रा', true),
(219, 13, 'स्टार्टअप', true),

-- Arabic Categories (id: 220 - 233)
(220, 14, 'العالم', true),
(221, 14, 'الشرق الأوسط', true),
(222, 14, 'الأعمال', true),
(223, 14, 'التكنولوجيا', true),
(224, 14, 'العلوم', true),
(225, 14, 'الصحة', true),
(226, 14, 'الرياضة', true),
(227, 14, 'كرة القدم', true),
(228, 14, 'الترفيه', true),
(229, 14, 'التعليم', true),
(230, 14, 'الثقافة', true),
(231, 14, 'السفر', true),
(232, 14, 'السيارات', true),
(233, 14, 'الشركات الناشئة', true),

-- French Categories (id: 234 - 250)
(234, 15, 'France', true),
(235, 15, 'Monde', true),
(236, 15, 'Europe', true),
(237, 15, 'Politique', true),
(238, 15, 'Économie', true),
(239, 15, 'Technologie', true),
(240, 15, 'Science', true),
(241, 15, 'Santé', true),
(242, 15, 'Sport', true),
(243, 15, 'Football', true),
(244, 15, 'Divertissement', true),
(245, 15, 'Éducation', true),
(246, 15, 'Culture', true),
(247, 15, 'Voyage', true),
(248, 15, 'Automobile', true),
(249, 15, 'Startups', true),
(250, 15, 'Actualités', true),

-- Spanish Categories (id: 251 - 267)
(251, 16, 'España', true),
(252, 16, 'Mundo', true),
(253, 16, 'Latinoamérica', true),
(254, 16, 'Política', true),
(255, 16, 'Economía', true),
(256, 16, 'Tecnología', true),
(257, 16, 'Ciencia', true),
(258, 16, 'Salud', true),
(259, 16, 'Deportes', true),
(260, 16, 'Fútbol', true),
(261, 16, 'Entretenimiento', true),
(262, 16, 'Educación', true),
(263, 16, 'Cultura', true),
(264, 16, 'Viajes', true),
(265, 16, 'Automóviles', true),
(266, 16, 'Startups', true),
(267, 16, 'Actualidad', true),

-- Filipino Categories (id: 268 - 285)
(268, 17, 'Pilipinas', true),
(269, 17, 'Metro Manila', true),
(270, 17, 'Mundo', true),
(271, 17, 'Pulitika', true),
(272, 17, 'Negosyo', true),
(273, 17, 'Teknolohiya', true),
(274, 17, 'Agham', true),
(275, 17, 'Kalusugan', true),
(276, 17, 'Palakasan', true),
(277, 17, 'Basketball', true),
(278, 17, 'Aliwan', true),
(279, 17, 'Edukasyon', true),
(280, 17, 'Kultura', true),
(281, 17, 'Pamumuhay', true),
(282, 17, 'Paglalakbay', true),
(283, 17, 'Sasakyan', true),
(284, 17, 'Startup', true),
(285, 17, 'Kasalukuyang Pangyayari', true)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, enabled = EXCLUDED.enabled;

-- Reset serial sequences for categories
SELECT setval('categories_id_seq', 285);

-- 3. Populating RSS Sources
INSERT INTO rss_sources (language_id, category_id, source_name, rss_url, enabled, priority) VALUES
-- English RSS Feeds
(1, 1, 'The Hindu - National', 'https://www.thehindu.com/news/national/feeder/default.rss', true, 1),
(1, 2, 'The Hindu - International', 'https://www.thehindu.com/news/international/feeder/default.rss', true, 1),
(1, 3, 'India Today - States', 'https://www.indiatoday.in/rss/1206500', true, 1),
(1, 4, 'India Today - Sports', 'https://www.indiatoday.in/rss/1206550', true, 1),
(1, 5, 'Times of India - Cricket', 'https://timesofindia.indiatimes.com/rssfeeds/54829575.cms', true, 1),
(1, 6, 'Times of India - Technology', 'https://timesofindia.indiatimes.com/rssfeeds/66949542.cms', true, 1),
(1, 7, 'Times of India - Business', 'https://timesofindia.indiatimes.com/rssfeeds/1898055.cms', true, 1),
(1, 8, 'NDTV Cooks - Health', 'https://feeds.feedburner.com/ndtvcooks-latest', true, 1),
(1, 10, 'Times of India - Science', 'https://timesofindia.indiatimes.com/rssfeeds/-2128672765.cms', true, 1),
(1, 11, 'Times of India - Education', 'https://timesofindia.indiatimes.com/rssfeeds/913168846.cms', true, 1),
(1, 12, 'Frontline - Economy', 'https://frontline.thehindu.com/economy/feeder/default.rss', true, 1),
(1, 13, 'News18 - Politics', 'https://www.news18.com/commonfeeds/v1/eng/rss/politics.xml', true, 1),
(1, 14, 'Times of India - Lifestyle', 'https://timesofindia.indiatimes.com/rssfeeds/2886704.cms', true, 1),
(1, 15, 'NDTV News - People', 'https://feeds.feedburner.com/ndtvnews-people', true, 1),
(1, 16, 'Frontline - Arts & Culture', 'https://frontline.thehindu.com/arts-and-culture/feeder/default.rss', true, 1),

-- Hindi RSS Feeds
(2, 17, 'Dainik Bhaskar - India', 'https://www.bhaskar.com/rss-v1--category-1061.xml', true, 1),
(2, 18, 'Dainik Bhaskar - World', 'https://www.bhaskar.com/rss-v1--category-1125.xml', true, 1),
(2, 19, 'News18 Hindi - States', 'https://hindi.news18.com/commonfeeds/v1/hin/rss/states.xml', true, 1),
(2, 20, 'Dainik Bhaskar - Sports', 'https://www.bhaskar.com/rss-v1--category-1053.xml', true, 1),
(2, 21, 'News18 Hindi - Cricket', 'https://hindi.news18.com/commonfeeds/v1/hin/rss/sports/cricket.xml', true, 1),
(2, 22, 'Dainik Bhaskar - Technology', 'https://www.bhaskar.com/rss-v1--category-5707.xml', true, 1),
(2, 23, 'Dainik Bhaskar - Business', 'https://www.bhaskar.com/rss-v1--category-1051.xml', true, 1),
(2, 24, 'News18 Hindi - Health', 'https://hindi.news18.com/commonfeeds/v1/hin/rss/lifestyle/health.xml', true, 1),
(2, 25, 'Dainik Bhaskar - Entertainment', 'https://www.bhaskar.com/rss-v1--category-3998.xml', true, 1),
(2, 26, 'Gadgets360 - Science', 'https://hindi.gadgets360.com/rss/science/news', true, 1),
(2, 27, 'India TV - Education', 'https://www.indiatv.in/rssnews/topstory-education.xml', true, 1),
(2, 28, 'India TV - Lifestyle', 'https://www.indiatv.in/rssnews/topstory-lifestyle.xml', true, 1),

-- Telugu RSS Feeds
(3, 29, 'News18 Telugu - Andhra Pradesh', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/andhra-pradesh.xml', true, 1),
(3, 30, 'News18 Telugu - Telangana', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/telangana.xml', true, 1),
(3, 31, 'News18 Telugu - India', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/national.xml', true, 1),
(3, 32, 'News18 Telugu - World', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/international.xml', true, 1),
(3, 33, 'News18 Telugu - Sports', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/sports.xml', true, 1),
(3, 34, 'News18 Telugu - Cricket', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/cricket.xml', true, 1),
(3, 35, 'News18 Telugu - Technology', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/technology.xml', true, 1),
(3, 36, 'News18 Telugu - Business', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/business.xml', true, 1),
(3, 37, 'News18 Telugu - Health', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/life-style/health.xml', true, 1),
(3, 38, 'OneIndia Telugu - Entertainment', 'https://telugu.oneindia.com/rss/feeds/telugu-entertainment-fb.xml', true, 1),
(3, 39, 'News18 Telugu - Science', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/science.xml', true, 1),
(3, 40, 'News18 Telugu - Politics', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/national/politics-national.xml', true, 1),
(3, 41, 'News18 Telugu - Lifestyle', 'https://telugu.news18.com/commonfeeds/v1/tel/rss/life-style.xml', true, 1),

-- Tamil RSS Feeds
(4, 42, 'News18 Tamil - Tamil Nadu', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/tamil-nadu.xml', true, 1),
(4, 43, 'Vikatan - India', 'https://www.vikatan.com/api/v1/collections/india-news.rss', true, 1),
(4, 44, 'Vikatan - World', 'https://www.vikatan.com/api/v1/collections/international.rss', true, 1),
(4, 45, 'News18 Tamil - Lifestyle', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/lifestyle.xml', true, 1),
(4, 46, 'News18 Tamil - Education', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/education.xml', true, 1),
(4, 47, 'News18 Tamil - Sports', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/sports.xml', true, 1),
(4, 48, 'News18 Tamil - Cricket', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/sports/cricket.xml', true, 1),
(4, 49, 'Vikatan - Technology', 'https://www.vikatan.com/stories.rss?section-id=8968', true, 1),
(4, 50, 'News18 Tamil - Business', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/business.xml', true, 1),
(4, 51, 'Vikatan - Health', 'https://www.vikatan.com/stories.rss?section-id=8963', true, 1),
(4, 52, 'Vikatan - Entertainment', 'https://www.vikatan.com/stories.rss?section-id=8956', true, 1),
(4, 53, 'Vikatan - Science', 'https://www.vikatan.com/stories.rss?section-id=8965', true, 1),
(4, 54, 'News18 Tamil - Automobile', 'https://tamil.news18.com/commonfeeds/v1/tam/rss/automobile.xml', true, 1),

-- Bengali RSS Feeds
(5, 55, 'OneIndia Bengali - West Bengal', 'https://bengali.oneindia.com/rss/feeds/bengali-news-fb.xml', true, 1),
(5, 55, 'Anandabazar - State', 'https://www.anandabazar.com/rss/state.xml', true, 1),
(5, 56, 'OneIndia Bengali - India', 'https://bengali.oneindia.com/rss/feeds/bengali-news-fb.xml?cat=india', true, 1),
(5, 56, 'Anandabazar - India', 'https://www.anandabazar.com/rss/india.xml', true, 1),
(5, 57, 'OneIndia Bengali - World', 'https://bengali.oneindia.com/rss/feeds/bengali-news-world-fb.xml', true, 1),
(5, 57, 'Anandabazar - International', 'https://www.anandabazar.com/rss/international.xml', true, 1),
(5, 58, 'Anandabazar - Politics', 'https://www.anandabazar.com/rss/politics.xml', true, 1),
(5, 58, 'OneIndia Bengali - Politics', 'https://bengali.oneindia.com/rss/feeds/bengali-news-fb.xml?cat=politics', true, 1),
(5, 59, 'Anandabazar - Business', 'https://www.anandabazar.com/rss/business.xml', true, 1),
(5, 59, 'OneIndia Bengali - Business', 'https://bengali.oneindia.com/rss/feeds/bengali-news-fb.xml?cat=business', true, 1),
(5, 60, 'OneIndia Bengali - Technology', 'https://bengali.oneindia.com/rss/feeds/bengali-gadgets-fb.xml', true, 1),
(5, 60, 'Anandabazar - Science & Tech', 'https://www.anandabazar.com/rss/science.xml', true, 1),
(5, 61, 'OneIndia Bengali - Health', 'https://bengali.oneindia.com/rss/feeds/bengali-lifestyle-fb.xml', true, 1),
(5, 61, 'Anandabazar - Lifestyle', 'https://www.anandabazar.com/rss/lifestyle.xml', true, 1),
(5, 62, 'OneIndia Bengali - Sports', 'https://bengali.oneindia.com/rss/feeds/bengali-sports-fb.xml', true, 1),
(5, 62, 'Anandabazar - Sports', 'https://www.anandabazar.com/rss/sports.xml', true, 1),
(5, 63, 'OneIndia Bengali - Cricket', 'https://bengali.oneindia.com/rss/feeds/bengali-sports-cricket-fb.xml', true, 1),
(5, 63, 'Anandabazar - Cricket', 'https://www.anandabazar.com/rss/cricket.xml', true, 1),
(5, 64, 'OneIndia Bengali - Entertainment', 'https://bengali.oneindia.com/rss/feeds/bengali-entertainment-fb.xml', true, 1),
(5, 64, 'Anandabazar - Entertainment', 'https://www.anandabazar.com/rss/entertainment.xml', true, 1),
(5, 65, 'OneIndia Bengali - Education', 'https://bengali.oneindia.com/rss/feeds/bengali-education-fb.xml', true, 1),
(5, 65, 'Anandabazar - Education', 'https://www.anandabazar.com/rss/career-and-education.xml', true, 1),

-- Gujarati RSS Feeds
(6, 66, 'OneIndia Gujarati - Gujarat', 'https://gujarati.oneindia.com/rss/feeds/gujarati-news-fb.xml?cat=gujarat', true, 1),
(6, 66, 'TV9 Gujarati - State', 'https://tv9gujarati.com/rss/state-news.xml', true, 1),
(6, 67, 'OneIndia Gujarati - India', 'https://gujarati.oneindia.com/rss/feeds/oneindia-gujarati-fb.xml?cat=india', true, 1),
(6, 67, 'TV9 Gujarati - National', 'https://tv9gujarati.com/rss/national-news.xml', true, 1),
(6, 68, 'OneIndia Gujarati - World', 'https://gujarati.oneindia.com/rss/feeds/gujarati-news-world-fb.xml', true, 1),
(6, 68, 'TV9 Gujarati - World', 'https://tv9gujarati.com/rss/world-news.xml', true, 1),
(6, 69, 'TV9 Gujarati - Politics', 'https://tv9gujarati.com/rss/politics-news.xml', true, 1),
(6, 69, 'OneIndia Gujarati - Politics', 'https://gujarati.oneindia.com/rss/feeds/oneindia-gujarati-fb.xml?cat=politics', true, 1),
(6, 70, 'TV9 Gujarati - Business', 'https://tv9gujarati.com/rss/business-news.xml', true, 1),
(6, 70, 'OneIndia Gujarati - Business', 'https://gujarati.oneindia.com/rss/feeds/gujarati-news-fb.xml?cat=business', true, 1),
(6, 71, 'OneIndia Gujarati - Technology', 'https://gujarati.oneindia.com/rss/feeds/gujarati-gadgets-fb.xml?cat=tech', true, 1),
(6, 71, 'TV9 Gujarati - Technology', 'https://tv9gujarati.com/rss/technology-news.xml', true, 1),
(6, 72, 'OneIndia Gujarati - Science', 'https://gujarati.oneindia.com/rss/feeds/gujarati-gadgets-fb.xml?cat=science', true, 1),
(6, 72, 'TV9 Gujarati - Science', 'https://tv9gujarati.com/rss/technology-news.xml?cat=science', true, 1),
(6, 73, 'OneIndia Gujarati - Health', 'https://gujarati.oneindia.com/rss/feeds/gujarati-lifestyle-fb.xml?cat=health', true, 1),
(6, 73, 'TV9 Gujarati - Health', 'https://tv9gujarati.com/rss/health-news.xml', true, 1),
(6, 74, 'OneIndia Gujarati - Sports', 'https://gujarati.oneindia.com/rss/feeds/gujarati-sports-fb.xml', true, 1),
(6, 74, 'TV9 Gujarati - Sports', 'https://tv9gujarati.com/rss/sports-news.xml', true, 1),
(6, 75, 'OneIndia Gujarati - Cricket', 'https://gujarati.oneindia.com/rss/feeds/gujarati-sports-cricket-fb.xml', true, 1),
(6, 75, 'TV9 Gujarati - Cricket', 'https://tv9gujarati.com/rss/cricket-news.xml', true, 1),
(6, 76, 'OneIndia Gujarati - Entertainment', 'https://gujarati.oneindia.com/rss/feeds/gujarati-entertainment-fb.xml', true, 1),
(6, 76, 'TV9 Gujarati - Entertainment', 'https://tv9gujarati.com/rss/entertainment-news.xml', true, 1),
(6, 77, 'OneIndia Gujarati - Education', 'https://gujarati.oneindia.com/rss/feeds/gujarati-education-fb.xml', true, 1),
(6, 77, 'TV9 Gujarati - Education', 'https://tv9gujarati.com/rss/education-news.xml', true, 1),
(6, 78, 'OneIndia Gujarati - Jobs', 'https://gujarati.oneindia.com/rss/feeds/gujarati-jobs-fb.xml', true, 1),
(6, 78, 'TV9 Gujarati - Jobs', 'https://tv9gujarati.com/rss/career-news.xml', true, 1),
(6, 79, 'OneIndia Gujarati - Auto', 'https://gujarati.oneindia.com/rss/feeds/gujarati-auto-fb.xml', true, 1),
(6, 79, 'TV9 Gujarati - Auto', 'https://tv9gujarati.com/rss/auto-news.xml', true, 1),
(6, 80, 'TV9 Gujarati - Agriculture', 'https://tv9gujarati.com/rss/agriculture-news.xml', true, 1),
(6, 80, 'OneIndia Gujarati - Agriculture', 'https://gujarati.oneindia.com/rss/feeds/gujarati-news-fb.xml?cat=agri', true, 1),

-- Kannada RSS Feeds
(7, 81, 'OneIndia Kannada - Karnataka', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml', true, 1),
(7, 81, 'OneIndia Kannada - Bengaluru', 'https://kannada.oneindia.com/rss/feeds/kannada-bengaluru-fb.xml', true, 1),
(7, 82, 'OneIndia Kannada - India', 'https://kannada.oneindia.com/rss/feeds/oneindia-kannada-fb.xml', true, 1),
(7, 82, 'OneIndia Kannada - National', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml?cat=india', true, 1),
(7, 83, 'OneIndia Kannada - World', 'https://kannada.oneindia.com/rss/feeds/kannada-news-world-fb.xml', true, 1),
(7, 83, 'OneIndia Kannada - Int', 'https://kannada.oneindia.com/rss/feeds/oneindia-kannada-fb.xml?cat=world', true, 1),
(7, 84, 'OneIndia Kannada - Politics', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml?cat=politics', true, 1),
(7, 85, 'OneIndia Kannada - Business', 'https://kannada.oneindia.com/rss/feeds/oneindia-kannada-fb.xml?cat=business', true, 1),
(7, 86, 'OneIndia Kannada - AI', 'https://kannada.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(7, 86, 'OneIndia Kannada - Gadgets', 'https://kannada.oneindia.com/rss/feeds/kannada-gadgets-fb.xml', true, 1),
(7, 87, 'OneIndia Kannada - Science AI', 'https://kannada.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=science', true, 1),
(7, 87, 'OneIndia Kannada - Science Gadgets', 'https://kannada.oneindia.com/rss/feeds/kannada-gadgets-fb.xml?cat=science', true, 1),
(7, 88, 'OneIndia Kannada - Lifestyle', 'https://kannada.oneindia.com/rss/feeds/kannada-lifestyle-fb.xml', true, 1),
(7, 88, 'OneIndia Kannada - Health', 'https://kannada.oneindia.com/rss/feeds/kannada-health-fb.xml', true, 1),
(7, 89, 'OneIndia Kannada - Sports', 'https://kannada.oneindia.com/rss/feeds/kannada-sports-fb.xml', true, 1),
(7, 89, 'OneIndia Kannada - Sports News', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml?cat=sports', true, 1),
(7, 90, 'OneIndia Kannada - Cricket', 'https://kannada.oneindia.com/rss/feeds/kannada-sports-cricket-fb.xml', true, 1),
(7, 90, 'OneIndia Kannada - Cricket Sports', 'https://kannada.oneindia.com/rss/feeds/kannada-sports-fb.xml?cat=cricket', true, 1),
(7, 91, 'OneIndia Kannada - Entertainment', 'https://kannada.oneindia.com/rss/feeds/kannada-entertainment-fb.xml', true, 1),
(7, 91, 'OneIndia Kannada - Movie News', 'https://kannada.oneindia.com/rss/feeds/kannada-movie-news-fb.xml', true, 1),
(7, 92, 'OneIndia Kannada - Movies', 'https://kannada.oneindia.com/rss/feeds/kannada-movie-news-fb.xml?cat=movies', true, 1),
(7, 92, 'OneIndia Kannada - Cinema', 'https://kannada.oneindia.com/rss/feeds/kannada-entertainment-fb.xml?cat=cinema', true, 1),
(7, 93, 'OneIndia Kannada - General Lifestyle', 'https://kannada.oneindia.com/rss/feeds/kannada-lifestyle-fb.xml?cat=lifestyle', true, 1),
(7, 94, 'OneIndia Kannada - Education', 'https://kannada.oneindia.com/rss/feeds/kannada-education-fb.xml', true, 1),
(7, 94, 'OneIndia Kannada - Edu Jobs', 'https://kannada.oneindia.com/rss/feeds/kannada-jobs-fb.xml?cat=education', true, 1),
(7, 95, 'OneIndia Kannada - Jobs', 'https://kannada.oneindia.com/rss/feeds/kannada-jobs-fb.xml', true, 1),
(7, 95, 'OneIndia Kannada - Career Edu', 'https://kannada.oneindia.com/rss/feeds/kannada-education-fb.xml?cat=jobs', true, 1),
(7, 96, 'OneIndia Kannada - Agri', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml?cat=agri', true, 1),
(7, 96, 'OneIndia Kannada - Agri Gen', 'https://kannada.oneindia.com/rss/feeds/oneindia-kannada-fb.xml?cat=agri', true, 1),
(7, 97, 'OneIndia Kannada - Auto', 'https://kannada.oneindia.com/rss/feeds/kannada-auto-fb.xml', true, 1),
(7, 97, 'OneIndia Kannada - Auto Tech', 'https://kannada.oneindia.com/rss/feeds/kannada-gadgets-fb.xml?cat=auto', true, 1),
(7, 98, 'OneIndia Kannada - Culture', 'https://kannada.oneindia.com/rss/feeds/kannada-news-fb.xml?cat=culture', true, 1),
(7, 98, 'OneIndia Kannada - Culture Gen', 'https://kannada.oneindia.com/rss/feeds/oneindia-kannada-fb.xml?cat=culture', true, 1),
(7, 99, 'OneIndia Kannada - Travel', 'https://kannada.oneindia.com/rss/feeds/kannada-travel-fb.xml', true, 1),
(7, 99, 'OneIndia Kannada - Travel Life', 'https://kannada.oneindia.com/rss/feeds/kannada-lifestyle-fb.xml?cat=travel', true, 1),

-- Malayalam RSS Feeds
(8, 100, 'OneIndia Malayalam - Kerala', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml', true, 1),
(8, 100, 'Onmanorama - Kerala', 'https://www.onmanorama.com/news/kerala.rss', true, 1),
(8, 101, 'OneIndia Malayalam - India', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=india', true, 1),
(8, 101, 'Onmanorama - India', 'https://www.onmanorama.com/news/india.rss', true, 1),
(8, 102, 'OneIndia Malayalam - World', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-world-fb.xml', true, 1),
(8, 102, 'Onmanorama - World', 'https://www.onmanorama.com/news/world.rss', true, 1),
(8, 103, 'Onmanorama - Politics (India)', 'https://www.onmanorama.com/news/india.rss?cat=politics', true, 1),
(8, 103, 'OneIndia Malayalam - Politics', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=politics', true, 1),
(8, 104, 'Onmanorama - Business', 'https://www.onmanorama.com/business.rss', true, 1),
(8, 104, 'OneIndia Malayalam - Business', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=business', true, 1),
(8, 105, 'OneIndia Malayalam - Tech AI', 'https://malayalam.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(8, 105, 'OneIndia Malayalam - Tech Gen', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=tech', true, 1),
(8, 106, 'OneIndia Malayalam - Science AI', 'https://malayalam.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=science', true, 1),
(8, 106, 'Onmanorama - Science World', 'https://www.onmanorama.com/news/world.rss?cat=science', true, 1),
(8, 107, 'OneIndia Malayalam - Health Life', 'https://malayalam.oneindia.com/rss/feeds/malayalam-lifestyle-fb.xml?cat=health', true, 1),
(8, 107, 'Onmanorama - Health', 'https://www.onmanorama.com/lifestyle/health.rss', true, 1),
(8, 108, 'OneIndia Malayalam - Sports', 'https://malayalam.oneindia.com/rss/feeds/malayalam-sports-fb.xml', true, 1),
(8, 108, 'Onmanorama - Sports', 'https://www.onmanorama.com/sports.rss', true, 1),
(8, 109, 'OneIndia Malayalam - Cricket', 'https://malayalam.oneindia.com/rss/feeds/malayalam-sports-cricket-fb.xml', true, 1),
(8, 109, 'Onmanorama - Cricket', 'https://www.onmanorama.com/sports/cricket.rss', true, 1),
(8, 110, 'OneIndia Malayalam - Entertainment', 'https://malayalam.oneindia.com/rss/feeds/malayalam-entertainment-fb.xml', true, 1),
(8, 110, 'Onmanorama - Entertainment', 'https://www.onmanorama.com/entertainment.rss', true, 1),
(8, 111, 'OneIndia Malayalam - Movies', 'https://malayalam.oneindia.com/rss/feeds/malayalam-movies-fb.xml', true, 1),
(8, 111, 'Onmanorama - Movie News', 'https://www.onmanorama.com/entertainment/movie-news.rss', true, 1),
(8, 112, 'OneIndia Malayalam - Lifestyle', 'https://malayalam.oneindia.com/rss/feeds/malayalam-lifestyle-fb.xml', true, 1),
(8, 112, 'Onmanorama - Lifestyle', 'https://www.onmanorama.com/lifestyle.rss', true, 1),
(8, 113, 'OneIndia Malayalam - Education', 'https://malayalam.oneindia.com/rss/feeds/malayalam-education-fb.xml', true, 1),
(8, 113, 'OneIndia Malayalam - Edu Jobs', 'https://malayalam.oneindia.com/rss/feeds/malayalam-jobs-fb.xml?cat=education', true, 1),
(8, 114, 'OneIndia Malayalam - Jobs', 'https://malayalam.oneindia.com/rss/feeds/malayalam-jobs-fb.xml', true, 1),
(8, 114, 'OneIndia Malayalam - Career Edu', 'https://malayalam.oneindia.com/rss/feeds/malayalam-education-fb.xml?cat=jobs', true, 1),
(8, 115, 'OneIndia Malayalam - Agri', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=agri', true, 1),
(8, 115, 'Onmanorama - Agri Kerala', 'https://www.onmanorama.com/news/kerala.rss?cat=agri', true, 1),
(8, 116, 'OneIndia Malayalam - Auto', 'https://malayalam.oneindia.com/rss/feeds/malayalam-auto-fb.xml', true, 1),
(8, 116, 'OneIndia Malayalam - Auto News', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=auto', true, 1),
(8, 117, 'OneIndia Malayalam - Culture', 'https://malayalam.oneindia.com/rss/feeds/malayalam-news-fb.xml?cat=culture', true, 1),
(8, 118, 'OneIndia Malayalam - Travel', 'https://malayalam.oneindia.com/rss/feeds/malayalam-travel-fb.xml', true, 1),
(8, 118, 'Onmanorama - Travel', 'https://www.onmanorama.com/lifestyle/travel.rss', true, 1),

-- Marathi RSS Feeds
(9, 119, 'OneIndia Marathi - Mumbai', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=mumbai', true, 1),
(9, 119, 'Lokmat - Mumbai', 'https://www.lokmat.com/rss/mumbai.xml', true, 1),
(9, 120, 'OneIndia Marathi - Maharashtra', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=maharashtra', true, 1),
(9, 120, 'Lokmat - Maharashtra', 'https://www.lokmat.com/rss/maharashtra.xml', true, 1),
(9, 121, 'OneIndia Marathi - India', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=india', true, 1),
(9, 121, 'Lokmat - National', 'https://www.lokmat.com/rss/national.xml', true, 1),
(9, 122, 'OneIndia Marathi - World', 'https://marathi.oneindia.com/rss/feeds/marathi-news-world-fb.xml', true, 1),
(9, 122, 'Lokmat - International', 'https://www.lokmat.com/rss/international.xml', true, 1),
(9, 123, 'Lokmat - Politics', 'https://www.lokmat.com/rss/politics.xml', true, 1),
(9, 123, 'OneIndia Marathi - Politics', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=politics', true, 1),
(9, 124, 'Lokmat - Business', 'https://www.lokmat.com/rss/business.xml', true, 1),
(9, 124, 'OneIndia Marathi - Business', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=business', true, 1),
(9, 125, 'OneIndia Marathi - Tech AI', 'https://marathi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(9, 125, 'OneIndia Marathi - Gadgets', 'https://marathi.oneindia.com/rss/feeds/marathi-gadgets-fb.xml', true, 1),
(9, 126, 'OneIndia Marathi - Science AI', 'https://marathi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=science', true, 1),
(9, 126, 'OneIndia Marathi - Science Gadgets', 'https://marathi.oneindia.com/rss/feeds/marathi-gadgets-fb.xml?cat=science', true, 1),
(9, 127, 'OneIndia Marathi - Health Life', 'https://marathi.oneindia.com/rss/feeds/marathi-lifestyle-fb.xml?cat=health', true, 1),
(9, 127, 'Lokmat - Health', 'https://www.lokmat.com/rss/health.xml', true, 1),
(9, 128, 'OneIndia Marathi - Women Life', 'https://marathi.oneindia.com/rss/feeds/marathi-lifestyle-fb.xml?cat=women', true, 1),
(9, 128, 'Lokmat - Women', 'https://www.lokmat.com/rss/women.xml', true, 1),
(9, 129, 'OneIndia Marathi - Sports', 'https://marathi.oneindia.com/rss/feeds/marathi-sports-fb.xml', true, 1),
(9, 129, 'Lokmat - Sports', 'https://www.lokmat.com/rss/sports.xml', true, 1),
(9, 130, 'OneIndia Marathi - Cricket', 'https://marathi.oneindia.com/rss/feeds/marathi-sports-cricket-fb.xml', true, 1),
(9, 130, 'Lokmat - Cricket', 'https://www.lokmat.com/rss/cricket.xml', true, 1),
(9, 131, 'OneIndia Marathi - Entertainment', 'https://marathi.oneindia.com/rss/feeds/marathi-entertainment-fb.xml', true, 1),
(9, 131, 'Lokmat - Entertainment', 'https://www.lokmat.com/rss/entertainment.xml', true, 1),
(9, 132, 'OneIndia Marathi - Movies', 'https://marathi.oneindia.com/rss/feeds/marathi-movies-fb.xml', true, 1),
(9, 132, 'OneIndia Marathi - Cinema', 'https://marathi.oneindia.com/rss/feeds/marathi-entertainment-fb.xml?cat=movies', true, 1),
(9, 133, 'OneIndia Marathi - Lifestyle', 'https://marathi.oneindia.com/rss/feeds/marathi-lifestyle-fb.xml', true, 1),
(9, 133, 'Lokmat - Lifestyle', 'https://www.lokmat.com/rss/lifestyle.xml', true, 1),
(9, 134, 'OneIndia Marathi - Education', 'https://marathi.oneindia.com/rss/feeds/marathi-education-fb.xml', true, 1),
(9, 134, 'OneIndia Marathi - Edu Jobs', 'https://marathi.oneindia.com/rss/feeds/marathi-jobs-fb.xml?cat=education', true, 1),
(9, 135, 'OneIndia Marathi - Jobs', 'https://marathi.oneindia.com/rss/feeds/marathi-jobs-fb.xml', true, 1),
(9, 135, 'OneIndia Marathi - Career Edu', 'https://marathi.oneindia.com/rss/feeds/marathi-education-fb.xml?cat=jobs', true, 1),
(9, 136, 'Lokmat - Agriculture', 'https://www.lokmat.com/rss/agriculture.xml', true, 1),
(9, 136, 'OneIndia Marathi - Agri News', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=agri', true, 1),
(9, 137, 'OneIndia Marathi - Auto', 'https://marathi.oneindia.com/rss/feeds/marathi-auto-fb.xml', true, 1),
(9, 137, 'OneIndia Marathi - Auto Gadgets', 'https://marathi.oneindia.com/rss/feeds/marathi-gadgets-fb.xml?cat=auto', true, 1),
(9, 138, 'OneIndia Marathi - Travel', 'https://marathi.oneindia.com/rss/feeds/marathi-travel-fb.xml', true, 1),
(9, 138, 'OneIndia Marathi - Travel Life', 'https://marathi.oneindia.com/rss/feeds/marathi-lifestyle-fb.xml?cat=travel', true, 1),
(9, 139, 'OneIndia Marathi - Culture', 'https://marathi.oneindia.com/rss/feeds/marathi-news-fb.xml?cat=culture', true, 1),
(9, 139, 'Lokmat - Culture Life', 'https://www.lokmat.com/rss/lifestyle.xml?cat=culture', true, 1),
(9, 140, 'OneIndia Marathi - Startups AI', 'https://marathi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=startups', true, 1),
(9, 140, 'Lokmat - Startups Biz', 'https://www.lokmat.com/rss/business.xml?cat=startups', true, 1),

-- Odia RSS Feeds
(10, 141, 'OneIndia Odia - Odisha', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml', true, 1),
(10, 141, 'Sambad - Odisha', 'https://sambad.in/feed', true, 1),
(10, 142, 'Sambad - Bhubaneswar', 'https://sambad.in/metro/feed', true, 1),
(10, 142, 'OneIndia Odia - Bhubaneswar', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=bhubaneswar', true, 1),
(10, 143, 'OneIndia Odia - India', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=india', true, 1),
(10, 143, 'Sambad - India', 'https://sambad.in/india-and-beyond/feed', true, 1),
(10, 144, 'OneIndia Odia - World', 'https://odia.oneindia.com/rss/feeds/odia-news-world-fb.xml', true, 1),
(10, 144, 'Sambad - World', 'https://sambad.in/international/feed', true, 1),
(10, 145, 'Sambad - Politics', 'https://sambad.in/politics/feed', true, 1),
(10, 145, 'OneIndia Odia - Politics', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=politics', true, 1),
(10, 146, 'Sambad - Business', 'https://sambad.in/business/feed', true, 1),
(10, 146, 'OneIndia Odia - Business', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=business', true, 1),
(10, 147, 'OneIndia Odia - Tech AI', 'https://odia.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(10, 147, 'Sambad - Tech', 'https://sambad.in/technology/feed', true, 1),
(10, 148, 'Sambad - Science', 'https://sambad.in/science/feed', true, 1),
(10, 148, 'OneIndia Odia - Science AI', 'https://odia.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=science', true, 1),
(10, 149, 'Sambad - Health', 'https://sambad.in/lifestyle/health/feed', true, 1),
(10, 149, 'OneIndia Odia - Health', 'https://odia.oneindia.com/rss/feeds/odia-lifestyle-fb.xml?cat=health', true, 1),
(10, 150, 'Sambad - Sports', 'https://sambad.in/sports/feed', true, 1),
(10, 150, 'OneIndia Odia - Sports', 'https://odia.oneindia.com/rss/feeds/odia-sports-fb.xml', true, 1),
(10, 151, 'OneIndia Odia - Cricket', 'https://odia.oneindia.com/rss/feeds/odia-sports-cricket-fb.xml', true, 1),
(10, 151, 'Sambad - Cricket', 'https://sambad.in/sports/feed?cat=cricket', true, 1),
(10, 152, 'OneIndia Odia - Entertainment', 'https://odia.oneindia.com/rss/feeds/odia-entertainment-fb.xml', true, 1),
(10, 152, 'Sambad - Entertainment', 'https://sambad.in/entertainment/feed', true, 1),
(10, 153, 'OneIndia Odia - Movies', 'https://odia.oneindia.com/rss/feeds/odia-entertainment-fb.xml?cat=movies', true, 1),
(10, 153, 'Sambad - Movies', 'https://sambad.in/entertainment/feed?cat=movies', true, 1),
(10, 154, 'OneIndia Odia - Education', 'https://odia.oneindia.com/rss/feeds/odia-education-fb.xml', true, 1),
(10, 154, 'Sambad - Education', 'https://sambad.in/career-and-campus/feed', true, 1),
(10, 155, 'OneIndia Odia - Jobs', 'https://odia.oneindia.com/rss/feeds/odia-jobs-fb.xml', true, 1),
(10, 155, 'Sambad - Jobs', 'https://sambad.in/career-and-campus/feed?cat=jobs', true, 1),
(10, 156, 'OneIndia Odia - Lifestyle', 'https://odia.oneindia.com/rss/feeds/odia-lifestyle-fb.xml', true, 1),
(10, 156, 'Sambad - Lifestyle', 'https://sambad.in/lifestyle/feed', true, 1),
(10, 157, 'Sambad - Agriculture', 'https://sambad.in/agriculture/feed', true, 1),
(10, 157, 'OneIndia Odia - Agriculture', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=agri', true, 1),
(10, 158, 'OneIndia Odia - Auto', 'https://odia.oneindia.com/rss/feeds/odia-auto-fb.xml', true, 1),
(10, 158, 'Sambad - Auto', 'https://sambad.in/auto/feed', true, 1),
(10, 159, 'Sambad - Culture', 'https://sambad.in/culture/feed', true, 1),
(10, 159, 'OneIndia Odia - Culture', 'https://odia.oneindia.com/rss/feeds/odia-news-fb.xml?cat=culture', true, 1),
(10, 160, 'OneIndia Odia - Travel', 'https://odia.oneindia.com/rss/feeds/odia-travel-fb.xml', true, 1),
(10, 160, 'Sambad - Travel', 'https://sambad.in/travel/feed', true, 1),
(10, 161, 'Sambad - Startups', 'https://sambad.in/business/feed?cat=startups', true, 1),
(10, 161, 'OneIndia Odia - Startups', 'https://odia.oneindia.com/rss/feeds/artificial-intelligence-fb.xml?cat=startups', true, 1),

-- Punjabi RSS Feeds
(11, 162, 'OneIndia Punjabi - Punjab', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 162, 'Punjabi Tribune - Punjab', 'https://www.punjabitribuneonline.com/feed/', true, 1),
(11, 163, 'Punjabi Tribune - Chandigarh', 'https://www.punjabitribuneonline.com/feed/', true, 1),
(11, 163, 'OneIndia Punjabi - Chandigarh', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 164, 'OneIndia Punjabi - India', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 164, 'Jagbani - National', 'https://www.jagbani.com/rss/news/national.xml', true, 1),
(11, 165, 'OneIndia Punjabi - World', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-world-fb.xml', true, 1),
(11, 165, 'Jagbani - International', 'https://www.jagbani.com/rss/news/international.xml', true, 1),
(11, 166, 'Jagbani - Politics', 'https://www.jagbani.com/rss/news/politics.xml', true, 1),
(11, 166, 'OneIndia Punjabi - Politics', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 167, 'Jagbani - Business', 'https://www.jagbani.com/rss/business.xml', true, 1),
(11, 167, 'OneIndia Punjabi - Business', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 168, 'OneIndia Punjabi - Tech AI', 'https://punjabi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(11, 168, 'Jagbani - Technology', 'https://www.jagbani.com/rss/technology.xml', true, 1),
(11, 169, 'OneIndia Punjabi - Science AI', 'https://punjabi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),
(11, 169, 'Jagbani - Science', 'https://www.jagbani.com/rss/technology.xml', true, 1),
(11, 170, 'OneIndia Punjabi - Health', 'https://punjabi.oneindia.com/rss/feeds/punjabi-lifestyle-fb.xml', true, 1),
(11, 170, 'Jagbani - Health', 'https://www.jagbani.com/rss/health.xml', true, 1),
(11, 171, 'OneIndia Punjabi - Sports', 'https://punjabi.oneindia.com/rss/feeds/punjabi-sports-fb.xml', true, 1),
(11, 171, 'Jagbani - Sports', 'https://www.jagbani.com/rss/sports.xml', true, 1),
(11, 172, 'OneIndia Punjabi - Cricket', 'https://punjabi.oneindia.com/rss/feeds/punjabi-sports-cricket-fb.xml', true, 1),
(11, 172, 'Jagbani - Cricket', 'https://www.jagbani.com/rss/cricket.xml', true, 1),
(11, 173, 'OneIndia Punjabi - Entertainment', 'https://punjabi.oneindia.com/rss/feeds/punjabi-entertainment-fb.xml', true, 1),
(11, 173, 'Jagbani - Entertainment', 'https://www.jagbani.com/rss/entertainment.xml', true, 1),
(11, 174, 'OneIndia Punjabi - Movies', 'https://punjabi.oneindia.com/rss/feeds/punjabi-entertainment-fb.xml', true, 1),
(11, 174, 'Jagbani - Movies', 'https://www.jagbani.com/rss/entertainment.xml', true, 1),
(11, 175, 'OneIndia Punjabi - Education', 'https://punjabi.oneindia.com/rss/feeds/punjabi-education-fb.xml', true, 1),
(11, 175, 'Jagbani - Career', 'https://www.jagbani.com/rss/career.xml', true, 1),
(11, 176, 'OneIndia Punjabi - Jobs', 'https://punjabi.oneindia.com/rss/feeds/punjabi-jobs-fb.xml', true, 1),
(11, 176, 'Jagbani - Jobs', 'https://www.jagbani.com/rss/career.xml', true, 1),
(11, 177, 'OneIndia Punjabi - Lifestyle', 'https://punjabi.oneindia.com/rss/feeds/punjabi-lifestyle-fb.xml', true, 1),
(11, 177, 'Jagbani - Lifestyle', 'https://www.jagbani.com/rss/lifestyle.xml', true, 1),
(11, 178, 'Jagbani - Agriculture', 'https://www.jagbani.com/rss/agriculture.xml', true, 1),
(11, 178, 'OneIndia Punjabi - Agriculture', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 179, 'OneIndia Punjabi - Auto', 'https://punjabi.oneindia.com/rss/feeds/punjabi-auto-fb.xml', true, 1),
(11, 179, 'Jagbani - Auto', 'https://www.jagbani.com/rss/auto.xml', true, 1),
(11, 180, 'Punjabi Tribune - Culture', 'https://www.punjabitribuneonline.com/feed/', true, 1),
(11, 180, 'OneIndia Punjabi - Culture', 'https://punjabi.oneindia.com/rss/feeds/punjabi-news-fb.xml', true, 1),
(11, 181, 'OneIndia Punjabi - Travel', 'https://punjabi.oneindia.com/rss/feeds/punjabi-travel-fb.xml', true, 1),
(11, 181, 'OneIndia Punjabi - Travel Life', 'https://punjabi.oneindia.com/rss/feeds/punjabi-lifestyle-fb.xml', true, 1),
(11, 182, 'Jagbani - Startups', 'https://www.jagbani.com/rss/business.xml', true, 1),
(11, 182, 'OneIndia Punjabi - Startups AI', 'https://punjabi.oneindia.com/rss/feeds/artificial-intelligence-fb.xml', true, 1),

-- Urdu RSS Feeds
(12, 183, 'UrduPoint - Pakistan', 'https://urdupoint.com/rss/pakistan.xml', true, 1),
(12, 183, 'BBC Urdu - Pakistan', 'https://www.bbc.com/urdu/index.xml', true, 1),
(12, 184, 'Inquilab - India', 'https://www.inquilab.com/rss/news.xml', true, 1),
(12, 184, 'UrduPoint - World (India)', 'https://urdupoint.com/rss/world.xml', true, 1),
(12, 185, 'UrduPoint - World', 'https://urdupoint.com/rss/world.xml', true, 1),
(12, 185, 'BBC Urdu - World', 'https://www.bbc.com/urdu/index.xml', true, 1),
(12, 186, 'Inquilab - Politics', 'https://www.inquilab.com/rss/news.xml', true, 1),
(12, 186, 'UrduPoint - Politics (Pakistan)', 'https://urdupoint.com/rss/pakistan.xml', true, 1),
(12, 187, 'UrduPoint - Business', 'https://urdupoint.com/rss/business.xml', true, 1),
(12, 187, 'Inquilab - Business', 'https://www.inquilab.com/rss/business.xml', true, 1),
(12, 188, 'UrduPoint - Technology', 'https://urdupoint.com/rss/technology.xml', true, 1),
(12, 188, 'BBC Urdu - Technology', 'https://www.bbc.com/urdu/index.xml', true, 1),
(12, 189, 'UrduPoint - Science', 'https://urdupoint.com/rss/science.xml', true, 1),
(12, 189, 'UrduPoint - Tech (Science)', 'https://urdupoint.com/rss/technology.xml', true, 1),
(12, 190, 'UrduPoint - Health', 'https://urdupoint.com/rss/health.xml', true, 1),
(12, 190, 'UrduPoint - Lifestyle (Health)', 'https://urdupoint.com/rss/lifestyle.xml', true, 1),
(12, 191, 'UrduPoint - Sports', 'https://urdupoint.com/rss/sports.xml', true, 1),
(12, 191, 'Inquilab - Sports', 'https://www.inquilab.com/rss/sports.xml', true, 1),
(12, 192, 'UrduPoint - Cricket', 'https://urdupoint.com/rss/cricket.xml', true, 1),
(12, 192, 'UrduPoint - Sports (Cricket)', 'https://urdupoint.com/rss/sports.xml', true, 1),
(12, 193, 'UrduPoint - Showbiz', 'https://urdupoint.com/rss/showbiz.xml', true, 1),
(12, 193, 'Inquilab - Entertainment', 'https://www.inquilab.com/rss/entertainment.xml', true, 1),
(12, 194, 'UrduPoint - Education', 'https://urdupoint.com/rss/education.xml', true, 1),
(12, 194, 'BBC Urdu - Education', 'https://www.bbc.com/urdu/index.xml', true, 1),
(12, 195, 'UrduPoint - Lifestyle', 'https://urdupoint.com/rss/lifestyle.xml', true, 1),
(12, 195, 'UrduPoint - Health (Lifestyle)', 'https://urdupoint.com/rss/health.xml', true, 1),
(12, 196, 'UrduPoint - Agriculture', 'https://urdupoint.com/rss/agriculture.xml', true, 1),
(12, 196, 'UrduPoint - Business (Agriculture)', 'https://urdupoint.com/rss/business.xml', true, 1),
(12, 197, 'UrduPoint - Auto', 'https://urdupoint.com/rss/auto.xml', true, 1),
(12, 197, 'UrduPoint - Tech (Auto)', 'https://urdupoint.com/rss/technology.xml', true, 1),
(12, 198, 'BBC Urdu - Culture', 'https://www.bbc.com/urdu/index.xml', true, 1),
(12, 198, 'UrduPoint - Lifestyle (Culture)', 'https://urdupoint.com/rss/lifestyle.xml', true, 1),
(12, 199, 'UrduPoint - Travel', 'https://urdupoint.com/rss/travel.xml', true, 1),
(12, 199, 'UrduPoint - Lifestyle (Travel)', 'https://urdupoint.com/rss/lifestyle.xml', true, 1),
(12, 200, 'UrduPoint - Business (Startups)', 'https://urdupoint.com/rss/business.xml', true, 1),
(12, 200, 'UrduPoint - Tech (Startups)', 'https://urdupoint.com/rss/technology.xml', true, 1),

-- Nepali RSS Feeds
(13, 201, 'OnlineKhabar - Nepal', 'https://www.onlinekhabar.com/feed', true, 1),
(13, 201, 'Ratopati - Nepal', 'https://www.ratopati.com/rss', true, 1),
(13, 202, 'OnlineKhabar - Kathmandu', 'https://www.onlinekhabar.com/feed?cat=kathmandu', true, 1),
(13, 202, 'Setopati - Kathmandu', 'https://www.setopati.com/feed?cat=kathmandu', true, 1),
(13, 203, 'OnlineKhabar - India', 'https://www.onlinekhabar.com/feed?cat=india', true, 1),
(13, 203, 'Kantipur - India', 'https://www.kantipur.com/rss?cat=india', true, 1),
(13, 204, 'OnlineKhabar - World', 'https://www.onlinekhabar.com/feed?cat=world', true, 1),
(13, 204, 'Kantipur - World', 'https://www.kantipur.com/rss?cat=world', true, 1),
(13, 205, 'Setopati - Politics', 'https://www.setopati.com/feed?cat=politics', true, 1),
(13, 205, 'Ratopati - Politics', 'https://www.ratopati.com/rss?cat=politics', true, 1),
(13, 206, 'OnlineKhabar - Business', 'https://www.onlinekhabar.com/feed?cat=business', true, 1),
(13, 206, 'Kantipur - Business', 'https://www.kantipur.com/rss?cat=business', true, 1),
(13, 207, 'OnlineKhabar - Technology', 'https://www.onlinekhabar.com/feed?cat=tech', true, 1),
(13, 207, 'Setopati - Technology', 'https://www.setopati.com/feed?cat=tech', true, 1),
(13, 208, 'OnlineKhabar - Science', 'https://www.onlinekhabar.com/feed?cat=science', true, 1),
(13, 208, 'Kantipur - Science', 'https://www.kantipur.com/rss?cat=science', true, 1),
(13, 209, 'OnlineKhabar - Health', 'https://www.onlinekhabar.com/feed?cat=health', true, 1),
(13, 209, 'Setopati - Health', 'https://www.setopati.com/feed?cat=health', true, 1),
(13, 210, 'OnlineKhabar - Sports', 'https://www.onlinekhabar.com/feed?cat=sports', true, 1),
(13, 210, 'Ratopati - Sports', 'https://www.ratopati.com/rss?cat=sports', true, 1),
(13, 211, 'OnlineKhabar - Cricket', 'https://www.onlinekhabar.com/feed?cat=cricket', true, 1),
(13, 211, 'Ratopati - Cricket', 'https://www.ratopati.com/rss?cat=cricket', true, 1),
(13, 212, 'OnlineKhabar - Entertainment', 'https://www.onlinekhabar.com/feed?cat=entertainment', true, 1),
(13, 212, 'Setopati - Entertainment', 'https://www.setopati.com/feed?cat=entertainment', true, 1),
(13, 213, 'OnlineKhabar - Education', 'https://www.onlinekhabar.com/feed?cat=education', true, 1),
(13, 213, 'Kantipur - Education', 'https://www.kantipur.com/rss?cat=education', true, 1),
(13, 214, 'OnlineKhabar - Lifestyle', 'https://www.onlinekhabar.com/feed?cat=lifestyle', true, 1),
(13, 214, 'Setopati - Lifestyle', 'https://www.setopati.com/feed?cat=lifestyle', true, 1),
(13, 215, 'OnlineKhabar - Agriculture', 'https://www.onlinekhabar.com/feed?cat=agriculture', true, 1),
(13, 215, 'Ratopati - Agriculture', 'https://www.ratopati.com/rss?cat=agriculture', true, 1),
(13, 216, 'OnlineKhabar - Automobile', 'https://www.onlinekhabar.com/feed?cat=auto', true, 1),
(13, 216, 'Kantipur - Automobile', 'https://www.kantipur.com/rss?cat=auto', true, 1),
(13, 217, 'Setopati - Culture', 'https://www.setopati.com/feed?cat=culture', true, 1),
(13, 217, 'Kantipur - Culture', 'https://www.kantipur.com/rss?cat=culture', true, 1),
(13, 218, 'OnlineKhabar - Travel', 'https://www.onlinekhabar.com/feed?cat=travel', true, 1),
(13, 218, 'Setopati - Travel', 'https://www.setopati.com/feed?cat=travel', true, 1),
(13, 219, 'OnlineKhabar - Startups', 'https://www.onlinekhabar.com/feed?cat=startups', true, 1),
(13, 219, 'Kantipur - Startups', 'https://www.kantipur.com/rss?cat=startups', true, 1),

-- Arabic RSS Feeds
(14, 220, 'Al Jazeera - World', 'https://www.aljazeera.net/aljazeerarss/ar/news.xml', true, 1),
(14, 220, 'BBC Arabic - World', 'https://feeds.bbci.co.uk/arabic/rss.xml', true, 1),
(14, 221, 'Al Jazeera - Middle East', 'https://www.aljazeera.net/aljazeerarss/ar/news.xml?cat=middleeast', true, 1),
(14, 221, 'CNN Arabic - Middle East', 'https://arabic.cnn.com/rss', true, 1),
(14, 222, 'Al Jazeera - Business', 'https://www.aljazeera.net/aljazeerarss/ar/ebusiness.xml', true, 1),
(14, 222, 'Aleqt - Business', 'https://www.aleqt.com/rss.xml', true, 1),
(14, 223, 'BBC Arabic - Technology', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=tech', true, 1),
(14, 223, 'CNN Arabic - Technology', 'https://arabic.cnn.com/rss?cat=tech', true, 1),
(14, 224, 'BBC Arabic - Science', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=science', true, 1),
(14, 224, 'Al Jazeera - Science', 'https://www.aljazeera.net/aljazeerarss/ar/news.xml?cat=science', true, 1),
(14, 225, 'BBC Arabic - Health', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=health', true, 1),
(14, 225, 'CNN Arabic - Health', 'https://arabic.cnn.com/rss?cat=health', true, 1),
(14, 226, 'Al Jazeera - Sports', 'https://www.aljazeera.net/aljazeerarss/ar/sport.xml', true, 1),
(14, 226, 'BBC Arabic - Sports', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=sports', true, 1),
(14, 227, 'Al Jazeera - Football', 'https://www.aljazeera.net/aljazeerarss/ar/sport.xml?cat=football', true, 1),
(14, 227, 'BBC Arabic - Football', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=football', true, 1),
(14, 228, 'CNN Arabic - Entertainment', 'https://arabic.cnn.com/rss?cat=entertainment', true, 1),
(14, 228, 'BBC Arabic - Entertainment', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=entertainment', true, 1),
(14, 229, 'BBC Arabic - Education', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=education', true, 1),
(14, 229, 'Al Jazeera - Education', 'https://www.aljazeera.net/aljazeerarss/ar/news.xml?cat=education', true, 1),
(14, 230, 'BBC Arabic - Culture', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=culture', true, 1),
(14, 230, 'Al Jazeera - Culture', 'https://www.aljazeera.net/aljazeerarss/ar/culture.xml', true, 1),
(14, 231, 'CNN Arabic - Travel', 'https://arabic.cnn.com/rss?cat=travel', true, 1),
(14, 231, 'BBC Arabic - Travel', 'https://feeds.bbci.co.uk/arabic/rss.xml?cat=travel', true, 1),
(14, 232, 'Al Jazeera - Auto', 'https://www.aljazeera.net/aljazeerarss/ar/news.xml?cat=auto', true, 1),
(14, 233, 'Aleqt - Startups', 'https://www.aleqt.com/rss.xml?cat=startups', true, 1),
(14, 233, 'CNN Arabic - Startups', 'https://arabic.cnn.com/rss?cat=startups', true, 1),

-- French RSS Feeds
(15, 234, 'Le Monde - France', 'https://www.lemonde.fr/rss/une.xml', true, 1),
(15, 234, 'Le Figaro - France', 'https://www.lefigaro.fr/rss/figaro_actualites.xml', true, 1),
(15, 235, 'France 24 - Monde', 'https://www.france24.com/fr/rss', true, 1),
(15, 235, 'Le Monde - Monde', 'https://www.lemonde.fr/international/rss_full.xml', true, 1),
(15, 236, 'France 24 - Europe', 'https://www.france24.com/fr/europe/rss', true, 1),
(15, 236, 'Le Monde - Europe', 'https://www.lemonde.fr/europe/rss_full.xml', true, 1),
(15, 237, 'Le Figaro - Politique', 'https://www.lefigaro.fr/rss/figaro_politique.xml', true, 1),
(15, 237, 'Le Monde - Politique', 'https://www.lemonde.fr/politique/rss_full.xml', true, 1),
(15, 238, 'Le Monde - Économie', 'https://www.lemonde.fr/economie/rss_full.xml', true, 1),
(15, 238, 'Les Echos - Économie', 'https://www.lesechos.fr/rss/rss_une.xml', true, 1),
(15, 239, 'France 24 - Technologie', 'https://www.france24.com/fr/sciences-technologies/rss', true, 1),
(15, 239, 'Le Monde - Technologie', 'https://www.lemonde.fr/pixels/rss_full.xml', true, 1),
(15, 240, 'France 24 - Science', 'https://www.france24.com/fr/sciences-technologies/rss?cat=science', true, 1),
(15, 240, 'Le Monde - Science', 'https://www.lemonde.fr/sciences/rss_full.xml', true, 1),
(15, 241, 'Le Monde - Santé', 'https://www.lemonde.fr/sante/rss_full.xml', true, 1),
(15, 241, 'France 24 - Santé', 'https://www.france24.com/fr/sciences-technologies/rss?cat=health', true, 1),
(15, 242, 'L\'Équipe - Sport', 'https://www.lequipe.fr/rss/actu_rss.xml', true, 1),
(15, 242, 'France 24 - Sport', 'https://www.france24.com/fr/sports/rss', true, 1),
(15, 243, 'L\'Équipe - Football', 'https://www.lequipe.fr/rss/actu_rss_Football.xml', true, 1),
(15, 243, 'France 24 - Football', 'https://www.france24.com/fr/sports/rss?cat=football', true, 1),
(15, 244, 'Le Figaro - Divertissement', 'https://www.lefigaro.fr/rss/figaro_culture.xml', true, 1),
(15, 244, 'France 24 - Divertissement', 'https://www.france24.com/fr/culture/rss', true, 1),
(15, 245, 'Le Monde - Éducation', 'https://www.lemonde.fr/campus/rss_full.xml', true, 1),
(15, 245, 'Le Figaro - Éducation', 'https://www.lefigaro.fr/rss/figaro_etudiant.xml', true, 1),
(15, 246, 'France 24 - Culture', 'https://www.france24.com/fr/culture/rss?cat=culture', true, 1),
(15, 246, 'Le Figaro - Culture', 'https://www.lefigaro.fr/rss/figaro_culture.xml?cat=culture', true, 1),
(15, 247, 'Le Figaro - Voyage', 'https://www.lefigaro.fr/rss/figaro_voyages.xml', true, 1),
(15, 247, 'France 24 - Voyage', 'https://www.france24.com/fr/rss?cat=travel', true, 1),
(15, 248, 'Le Figaro - Automobile', 'https://www.lefigaro.fr/rss/figaro_auto.xml', true, 1),
(15, 248, 'Les Echos - Automobile', 'https://www.lesechos.fr/rss/rss_une.xml?cat=auto', true, 1),
(15, 249, 'Les Echos - Startups', 'https://www.lesechos.fr/rss/rss_une.xml?cat=startups', true, 1),
(15, 249, 'Le Monde - Startups', 'https://www.lemonde.fr/economie/rss_full.xml?cat=startups', true, 1),

-- Spanish RSS Feeds
(16, 251, 'El País - España', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada', true, 1),
(16, 251, 'El Mundo - España', 'https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml', true, 1),
(16, 252, 'El País - Mundo', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada', true, 1),
(16, 252, 'France 24 - Mundo', 'https://www.france24.com/es/rss', true, 1),
(16, 253, 'El País - Latinoamérica', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/america/portada', true, 1),
(16, 253, 'BBC Mundo - Latinoamérica', 'https://www.bbc.com/mundo/index.xml', true, 1),
(16, 254, 'El País - Política', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/espana/politica/portada', true, 1),
(16, 254, 'El Mundo - Política', 'https://e00-elmundo.uecdn.es/elmundo/rss/espana.xml', true, 1),
(16, 255, 'El País - Economía', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada', true, 1),
(16, 255, 'El Economista - Economía', 'https://www.eleconomista.es/rss/rss-empresas.php', true, 1),
(16, 256, 'El País - Tecnología', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada', true, 1),
(16, 256, 'Xataka - Tecnología', 'https://www.xataka.com/feedburner.xml', true, 1),
(16, 257, 'El País - Ciencia', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada', true, 1),
(16, 257, 'Muy Interesante - Ciencia', 'https://www.muyinteresante.com/rss/', true, 1),
(16, 258, 'El País - Salud', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/salud-y-bienestar/portada', true, 1),
(16, 258, 'Muy Interesante - Salud', 'https://www.muyinteresante.com/rss/?cat=salud', true, 1),
(16, 259, 'El País - Deportes', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/deportes/portada', true, 1),
(16, 259, 'Marca - Deportes', 'https://e00-marca.uecdn.es/rss/portada.xml', true, 1),
(16, 260, 'Marca - Fútbol', 'https://e00-marca.uecdn.es/rss/futbol.xml', true, 1),
(16, 260, 'El País - Fútbol', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/deportes/portada?cat=futbol', true, 1),
(16, 261, 'El País - Entretenimiento', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/cultura/portada?cat=ent', true, 1),
(16, 261, 'Europa Press - Entretenimiento', 'https://www.europapress.es/rss/rss.aspx?ch=00066', true, 1),
(16, 262, 'El País - Educación', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/educacion/portada', true, 1),
(16, 262, 'Europa Press - Educación', 'https://www.europapress.es/rss/rss.aspx', true, 1),
(16, 263, 'El País - Cultura', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/cultura/portada', true, 1),
(16, 263, 'France 24 - Cultura', 'https://www.france24.com/es/rss?cat=cultura', true, 1),
(16, 264, 'El Viajero - Viajes', 'https://www.elviajero.elpais.com/rss/', true, 1),
(16, 264, 'El País - Viajes', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada?cat=viajes', true, 1),
(16, 265, 'Motorpasión - Automóviles', 'https://www.motorpasion.com/index.xml', true, 1),
(16, 265, 'Coches.net - Automóviles', 'https://www.coches.net/rss/', true, 1),
(16, 266, 'El Economista - Startups', 'https://www.eleconomista.es/rss/rss-empresas.php?cat=startups', true, 1),
(16, 266, 'El País - Startups', 'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada?cat=startups', true, 1),

-- Filipino RSS Feeds
(17, 268, 'Philstar - Pilipinas', 'https://www.philstar.com/rss/headlines', true, 1),
(17, 268, 'GMA News - Pilipinas', 'https://www.gmanetwork.com/news/rss/news/nation/feed.xml', true, 1),
(17, 269, 'GMA News - Metro Manila', 'https://www.gmanetwork.com/news/rss/news/metro/feed.xml', true, 1),
(17, 269, 'Philstar - Metro Manila', 'https://www.philstar.com/rss/headlines?cat=metromanila', true, 1),
(17, 270, 'GMA News - Mundo', 'https://www.gmanetwork.com/news/rss/news/world/feed.xml', true, 1),
(17, 270, 'Philstar - Mundo', 'https://www.philstar.com/rss/world', true, 1),
(17, 271, 'Philstar - Pulitika', 'https://www.philstar.com/rss/headlines?cat=politics', true, 1),
(17, 271, 'GMA News - Pulitika', 'https://www.gmanetwork.com/news/rss/news/nation/feed.xml?cat=politics', true, 1),
(17, 272, 'Philstar - Negosyo', 'https://www.philstar.com/rss/business', true, 1),
(17, 272, 'GMA News - Negosyo', 'https://www.gmanetwork.com/news/rss/money/feed.xml', true, 1),
(17, 273, 'GMA News - Teknolohiya', 'https://www.gmanetwork.com/news/rss/scitech/feed.xml', true, 1),
(17, 273, 'Philstar - Teknolohiya', 'https://www.philstar.com/rss/technology', true, 1),
(17, 274, 'GMA News - Agham', 'https://www.gmanetwork.com/news/rss/scitech/feed.xml?cat=science', true, 1),
(17, 274, 'Philstar - Agham', 'https://www.philstar.com/rss/technology?cat=science', true, 1),
(17, 275, 'GMA News - Kalusugan', 'https://www.gmanetwork.com/news/rss/lifestyle/healthandwellness/feed.xml', true, 1),
(17, 275, 'Philstar - Kalusugan', 'https://www.philstar.com/rss/lifestyle?cat=health', true, 1),
(17, 276, 'GMA News - Palakasan', 'https://www.gmanetwork.com/news/rss/sports/feed.xml', true, 1),
(17, 276, 'Philstar - Palakasan', 'https://www.philstar.com/rss/sports', true, 1),
(17, 277, 'GMA News - Basketball', 'https://www.gmanetwork.com/news/rss/sports/feed.xml?cat=basketball', true, 1),
(17, 277, 'Philstar - Basketball', 'https://www.philstar.com/rss/sports?cat=basketball', true, 1),
(17, 278, 'GMA News - Aliwan', 'https://www.gmanetwork.com/news/rss/showbiz/feed.xml', true, 1),
(17, 278, 'Philstar - Aliwan', 'https://www.philstar.com/rss/entertainment', true, 1),
(17, 279, 'Philstar - Edukasyon', 'https://www.philstar.com/rss/headlines?cat=education', true, 1),
(17, 279, 'GMA News - Edukasyon', 'https://www.gmanetwork.com/news/rss/news/nation/feed.xml?cat=education', true, 1),
(17, 280, 'GMA News - Kultura', 'https://www.gmanetwork.com/news/rss/lifestyle/feed.xml?cat=culture', true, 1),
(17, 280, 'Philstar - Kultura', 'https://www.philstar.com/rss/lifestyle?cat=culture', true, 1),
(17, 281, 'GMA News - Pamumuhay', 'https://www.gmanetwork.com/news/rss/lifestyle/feed.xml', true, 1),
(17, 281, 'Philstar - Pamumuhay', 'https://www.philstar.com/rss/lifestyle', true, 1),
(17, 282, 'GMA News - Paglalakbay', 'https://www.gmanetwork.com/news/rss/lifestyle/feed.xml?cat=travel', true, 1),
(17, 282, 'Philstar - Paglalakbay', 'https://www.philstar.com/rss/lifestyle?cat=travel', true, 1),
(17, 283, 'TopGear - Sasakyan', 'https://www.topgear.com.ph/rss', true, 1),
(17, 283, 'Philstar - Sasakyan', 'https://www.philstar.com/rss/business?cat=auto', true, 1),
(17, 284, 'GMA News - Startup', 'https://www.gmanetwork.com/news/rss/money/feed.xml?cat=startup', true, 1),
(17, 284, 'Philstar - Startup', 'https://www.philstar.com/rss/business?cat=startup', true, 1)
ON CONFLICT (rss_url) DO NOTHING;
